compose:
  ReusedModifierInstance:
    active: true
  UnnecessaryEventHandlerParameter:
    active: true
  ComposableEventParameterNaming:
    active: true
  ComposableParametersOrdering:
    active: true
  ModifierHeightWithText:
    active: true
  MissingModifierDefaultValue:
    active: true
  PublicComposablePreview:
    active: true
  TopLevelComposableFunctions:
    active: true
    allowInObjects: false
  ComposableFunctionName:
    active: true
  ConditionCouldBeLifted:
    active: true
    ignoreCallsWithArgumentNames: [ 'modifier', 'contentAlignment' ]

naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: '^[a-zA-Z][a-zA-Z0-9]*'
    ignoreAnnotated: ['Composable']

style:
  active: true
  NewLineAtEndOfFile:
    active: true
    autoCorrect: true
  UnusedImports:
    active: true
    autoCorrect: true
